### PR TITLE
docs: `2024.1` release notes 

### LINKED ISSUE #68: 2024.1 release notes placeholder
This is release notes placeholder for the upcoming `2024.1` version. 

I'll also use this issue to include other related relase notes reminders.

### PR DESCRIPTION
**Pull request by viniarck**
Closes #68 

### Summary

`2024.1` release notes

### Local Tests

Generated locally, it rendered correctly:

### End-to-End Tests

N/A

### CODE REVIEW

**Review by Alopalao — APPROVED** [review]
Looks good to me.

**Comment by viniarck** [comment]
> Looks good to me.

Cool. Appreciated your review.

**Comment by Ktmi** [comment]
Looks good to me

**Comment by viniarck** [comment]
> Looks good to me

Cool. Appreciated your review.

**Pull request merged**
