### PR TITLE
doc: Updated `"Local Tests"` information

### PR DESCRIPTION
**Pull request by viniarck**
### Summary

<s>Renamed `"Local Tests"` as `"Exploratory Tests"` to be clearer. </s>

- Updated "Local Tests" information with an example for clarity
- Added colon on PR title

> - `### Exploratory Tests` subsection is for documenting and explaining how you've validated and explored your change locally with `kytosd` in addition to shipping unit tests

### CODE REVIEW

**Comment by viniarck** [comment]
We could also call it `"Local Exploratory Tests"`, or if you have any other suggestions let me know.

**Comment by Alopalao** [comment]
I think the name `Local Tests` is fine as long as the example shown [here](https://kytos-ng.github.io/procedures/prs.html#submitting-a-pr) gives a real example on what is expected.
```
### Local Tests
Added new event:
2028-02-03 13:07:37,694 - INFO [kytos.napps.kytos/new_napp] (thread_pool_app_23) Event my_new_event Packet(343) received.                  
```      
To be honest the first time I read that page I thought I completely understood what `Local Tests` meant so I stopped reading, completely missing the explanation later. But if you want to be more direct with the name what about "Kytos console Tests"?

**Comment by viniarck** [comment]
> I think the name `Local Tests` is fine as long as the example shown [here](https://kytos-ng.github.io/procedures/prs.html#submitting-a-pr) gives a real example on what is expected.
> 
> ```
> ### Local Tests
> Added new event:
> 2028-02-03 13:07:37,694 - INFO [kytos.napps.kytos/new_napp] (thread_pool_app_23) Event my_new_event Packet(343) received.                  
> ```
> 
> To be honest the first time I read that page I thought I completely understood what `Local Tests` meant so I stopped reading, completely missing the explanation later. But if you want to be more direct with the name what about `"Kytos console Tests"`?

Aldo, that's also an option, we can keep as it is. Regarding the example in the template, I'd like to keep them a bit more open just so folks don't immediately think that they need to collect the logs, even though often times that might be what they need. For instance, some times if e2e tests don't have coverage yet, maybe they'll want to also post request / response tests with curl. 

We could also explain this part about the console though that you mentioned, since ultimately, it's great that developers keep an eye on it to also check for tracebacks (since not every time a request will be involved with a 500 response in the worst case)

**Comment by viniarck** [comment]
Aldo, I've just pushed a new commit augmenting more info https://github.com/kytos-ng/kytos-ng.github.io/pull/47/commits/b899556b50f87ef3a95c255f94d1bafffd90a736. 

Regarding keeping the name as it is let's see if more folks will want to keep them as `"Local Tests"`.

**Comment by viniarck** [comment]
@Alopalao could you review again?

I've pushed https://github.com/kytos-ng/kytos-ng.github.io/pull/47/commits/d1d5e8ca1cc7fd3707cac54aa504cbb809164a23 reverting back to "Local Tests" since most of the team is comfortable with it. Also, I took the opportunity o add a colon ":" in the PR title, using like doc: feature: fix: instead of [doc], [feature], [doc] is more convenient. 

I've also updated and edited the PR summary for the record

**Comment by Alopalao** [comment]
Sure, LGTM

**Review by Alopalao — COMMENTED** [review]
Sure, LGTM

**Review by Alopalao — APPROVED** [review]

**Comment by viniarck** [comment]
> Sure, LGTM

Thanks for your review and inputs @Alopalao. Let's ship this.

**Pull request merged**
